#!/bin/bash
echo ""
echo "**********************************************************"
echo "           Welcome to your first time setup!             *"
echo "  I will attempt to download all of your basic packages  *"
echo "**********************************************************"
echo ""
sudo apt install openjdk-11-headless
sudo apt install openjdk-11-jdk
sudo apt install openjfx
sudo apt install gcc
sudo apt install g++
sudo apt install ant
sudo apt install python
sudo apt install automake
sudo apt install cmake
sudo apt install autoconf
sudo apt install pulseaudio
sudo apt install ffmpegthumbnailer
sudo apt install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
echo ""
echo "****************************"
echo "*     All finished! :)     *"
echo "*  Welcome to your new OS  *"
echo "****************************"
echo ""
